repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: "23.1.0"
    hooks:
      - id: black
        files: "^MemAnalysis|^tests"

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.4.1"
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli

  # - repo: https://github.com/citation-file-format/cffconvert
  #   rev: 054bda51dbe278b3e86f27c890e3f3ac877d616c
  #   hooks:
  #     - id: validate-cff

  - repo: local
    hooks:
      - id: check-copyright
        name: Check copyright
        entry: ./devtools/copyright-precommit-check.sh
        language: script
