[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "MemAnalysis"
authors = [
    { name = "Carolina Sarto", email = "csarto@ucsd.edu" },
    { name = "Christopher T. Lee", email = "ctlee@ucsd.edu" },
]
description = "MemAnalysis"
readme = "README.md"
requires-python = ">=3.9"
keywords = []
license = { text = "Mozilla Public License 2.0 (MPL 2.0)" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Visualization",
]
dependencies = []
dynamic = ["version"]

[tool.hatch]
version.source = "vcs"
version.raw_options.version_scheme = "guess-next-dev"
version.raw_options.local_scheme = "node-and-date"
build.hooks.vcs.version-file = "MemAnalysis/_version.py"
[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tool.pixi.pypi-dependencies]
MemAnalysis = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
python = ">=3.14.0,<3.15"
mdanalysis = ">=2.10.0,<3"
numpy = ">=2.3.3,<3"

[tool.pixi.feature.test.dependencies]
pytest = "*"

[tool.pixi.feature.test.tasks]
tests = "pytest"
tests-verbose = "pytest -v"

[tool.pixi.environments]
default = { solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
